clone_depth: 1
environment:
  matrix:
    - nodejs_version: "11"

version: "{build}"
build: off
deploy: off

branches:
  only:
    - master
    - /issue-.*/

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - node --version
  - npm --version

test_script:
  - npm test
