name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: NPM Install & lerna Bootstrap
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build
    - name: Test
      if: ${{ matrix.node-version != 'latest' || github.ref_name != 'master' }}
      run: npm test
    - name: Test & Report coverage
      if: ${{ matrix.node-version == 'latest' && github.ref_name == 'master' }}
      run: npm run report
